name: Deploy to Firebase Hosting on push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install app dependencies
        working-directory: ./app
        env:
          npm_config_production: 'false'
        run: npm ci
      - name: Build app
        working-directory: ./app
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LEARN_DOCKER_E4749 }}
          channelId: live
          projectId: learn-docker-e4749
        env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
